version: '3.8'

services:
  mongodb:
    image: mongo:4.4.6
    container_name: farmaa-mongodb
    restart:  unless-stopped
    ports:
      - 27017:27017
    volumes:
      - farmaa_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: farmaaDB

  # backend:
  #   image: node:22
  #   container_name: farmaa-backend
  #   restart: unless-stopped
  #   working_dir: /usr/src/app
  #   command: sh -c "npm install && node server.js"
  #   ports:
  #     - 3000:3000
  #   env_file:
  #     - ./backend/.env
  #   depends_on:
  #     - mongodb
  #   volumes:
  #     - ./backend:/usr/src/app

  # frontend:
  #   image: nginx:alpine
  #   container_name: farmaa-frontend
  #   restart: unless-stopped
  #   ports:
  #     - 80:80
  #   depends_on:
  #   - backend
  #   volumes:
  #     - ./frontend:/usr/share/nginx/html:ro

volumes:
  farmaa_data:
